# Generated by Django 4.0.3 on 2022-09-07 21:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kadai',
            fields=[
                ('kadai_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission_deadline', models.DateTimeField()),
                ('kadai_desc', models.TextField()),
                ('question_cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KadaiQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField()),
                ('question_state', models.TextField()),
                ('question_type', models.CharField(max_length=100)),
                ('is_multiple', models.BooleanField(blank=True)),
                ('kadai_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pls.kadai')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('usertype', models.BooleanField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(blank=True)),
                ('point', models.IntegerField()),
                ('kadai_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pls.kadai')),
                ('question_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pls.kadaiquestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_item_index', models.CharField(max_length=20)),
                ('question_item_content', models.TextField()),
                ('multiple_points', models.BooleanField(blank=True)),
                ('is_appropriate', models.IntegerField()),
                ('kadai_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pls.kadai')),
                ('question_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pls.kadaiquestion')),
            ],
        ),
        migrations.CreateModel(
            name='KadaiAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kadai_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pls.kadai')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pls.users')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_answer', models.TextField(blank=True)),
                ('question_answer_file', models.FileField(blank=True, upload_to='uploaded_file/%Y/%m/%d')),
                ('kadai_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pls.kadai')),
                ('question_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pls.kadaiquestion')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pls.users')),
            ],
        ),
    ]
